dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install 
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --disable-pytest-warnings --cov=sharkgate
after_success:
  - coveralls